### ISSUE TITLE
timeout parameter should have been a time.Duration

### ISSUE THREAD

**Issue by riking** [ammario/mcping#1]
The `timeout` parameter should have been a `time.Duration`.

Please don't change the existing function, instead add a 

    func PingWithTimeout(addr string, timeout time.Duration) (PingResponse, error)

as that's more in line with standard naming conventions.

Alternately, this would also be fine:

    func PingWithContext(ctx context.Context, addr string) (PingResponse, error)

**Comment by ammario** [comment]
You're absolutely correct, this library needs a overhaul, I'll try to renovate today.

**Comment by riking** [comment]
Also, for some reason, this seems to fail:

	// m.Port = 25569
	pingResponse, err := mcping.Ping(fmt.Sprintf("localhost:%d", m.Port))
	// $ telnet localhost 25569
	Trying ::1...
	Connected to localhost.
	Escape character is '^]'.
	^]q

**Comment by ammario** [comment]
Both issues resolved
